import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { usePathname } from "next/navigation";
import { shouldHideNavbar } from "@/checkPath";

export const metadata: Metadata = {
  title: "UNINAV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {!shouldHideNavbar && <Navbar />}
        {children}
      </body>
    </html>
  );
}
