"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/authContext";
import QueryProvider from "@/tanstack/QueryProvider";
import { Toaster } from "react-hot-toast";
import ConditionalNavbar from "@/components/ConditionalNavbar";
import { BookmarksProvider } from "@/contexts/bookmarksContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "UNINAV",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <AuthProvider>
            <ConditionalNavbar />
            <BookmarksProvider>{children}</BookmarksProvider>
          </AuthProvider>
        </QueryProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
