import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/tanstack/QueryProvider";
import { Toaster } from "react-hot-toast";
import ConditionalNavbar from "@/components/checkPath";
import { AuthProvider } from "@/contexts/authContext";

export const metadata: Metadata = {
  title: "UNINAV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ConditionalNavbar />
        <AuthProvider>
          <QueryProvider>{children}</QueryProvider>
        </AuthProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
